version: "3.7"

services:
  app:
    image: php_custom
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: php_postgres

  postgres:
    image: postgres
    volumes:
      - todo-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: php_postgres

volumes:
  todo-postgres-data:
